runmode: release                 # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
tls:
  addr: :8081
  cert: conf/server.crt
  key: conf/server.key
log:
#  writers: stdout
  writers: file
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: true
  rollingPolicy: daily
  log_rotate_date: 1
  log_rotate_size: 10
  log_backup_count: 7
db:
  name: db_apiserver
  addr: go-mysql:3306
  username: root
  password: root
  prefix: manager_
docker_db:
  name: db_apiserver
  addr: go-mysql:3306
  username: root
  password: root

redis:
  maxidle: 16 #最初的连接数量
  maxactive: 0    #连接池最大连接数量,不确定可以用0（0表示自动定义），按需分配
  idletimeout: 300  #连接关闭时间 300秒 （300秒不使用自动关闭）
  host: go-redis
  port: 6379
